### ISSUE TITLE
Forge dependency is broken for SpongeForge

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/SpongeDownloads#6]
We recently had to change the dependency resolution for [SF downloads in this commit](https://github.com/SpongePowered/SpongeForge/commit/1544c736731f603d7818e5aff1db7090a2085fd9), and it's broken the Forge tag for these downloads. Instead of stating Forge 2768, it states Forge 23.

I'm guessing this is something that needs to be fixed in the indexer - but if not, apologies if this is in the wrong place.

**Comment by Minecrell** [comment]
This change will be annoying for consumers of the downloads API, but it mainly needs to be fixed here in the frontend. The backend exposes dependencies as-is.
